// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/aliffatulmf/mkp-eticket-service/internal/auth"
	"github.com/aliffatulmf/mkp-eticket-service/internal/handler"
	"github.com/aliffatulmf/mkp-eticket-service/internal/repository"
	"github.com/aliffatulmf/mkp-eticket-service/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func NewTerminalHandler(db *pgxpool.Pool) handler.TerminalHandler {
	terminalRepository := repository.NewTerminalRepository(db)
	terminalService := service.NewTerminalService(terminalRepository)
	terminalHandler := handler.NewTerminalHandler(terminalService)
	return terminalHandler
}

func NewAuthHandler(db *pgxpool.Pool, jwtSecret string) handler.AuthHandler {
	adminRepository := repository.NewAdminRepository(db)
	adminService := service.NewAdminService(adminRepository)
	authService := auth.NewService(jwtSecret)
	authHandler := handler.NewAuthHandler(adminService, authService)
	return authHandler
}

func NewAdminHandler(db *pgxpool.Pool) handler.AdminHandler {
	adminRepository := repository.NewAdminRepository(db)
	adminService := service.NewAdminService(adminRepository)
	adminHandler := handler.NewAdminHandler(adminService)
	return adminHandler
}
